#!/bin/sh

## hyphop ##

. ./,config

# https://git.kernel.org/pub/scm/utils/dtc/dtc.git/
# git clone git://git.kernel.org/pub/scm/utils/dtc/dtc.git $dtc

v="v1.4.4"
v="v1.4.3"

cmd="git clone --depth 1 git://git.kernel.org/pub/scm/utils/dtc/dtc.git $dtc"
echo $cmd
$cmd

p=$PWD
echo $p
cd $dtc
git checkout $v
cd $p

rm -r $dtc/.git

make -C $dtc -j 4

# 1.4.4
#make all  -j 8

