#!/bin/sh

## hyphop ##

. ./,config

#w=uboot-mizy.rw
#r=uboot-mizy.ro

w=$src.rw
r=$src.ro

mode=$1
ext=$2
[ "$ext" = "" ] && ext=c

out="&1"

[ "$mode" ] && {
    out=",tmp/"
    i=0
}

for f in `find $w -type f -name \*.$ext -printf %P\\\\n`; do

    printf "== %-32s ==> %2s\n" $f $i 1>&2
    
    eval "diff -pruN '$r/$f' '$w/$f' >$out$i"

    [ "$mode" ] && i=$((i+1))

done
