#!/bin/sh

## hyphop ##

. ./,config

[ -s $src/Makefile ] || { 
    git clone --depth 1 -b v2017.01 https://github.com/RobertCNelson/u-boot $src
    rm -rd $src/.git
}

[ -x $dtc/dtc ] || ./dtc_prepare_make


arm-openwrt-linux-gcc --version > /dev/null || {
    cd ..
    [ -s $tc_gcc.tar.bz2 ] ||  wget $tc_src
    tar -xf $tc_gcc.tar.bz2
    ln -s $tc_gcc/$tc_gcc_dir $tc_gcc_dir
}

cd $bdir

#exit;

#ls -l1 $patches/

cd $src
cat ../$patches/*.patch | patch -p1
rm configs/*
cp -a ../$add/* .
cd ..

./uboot_defconfig
